### ISSUE TITLE
NetworkOnMainThreadException 醉了

### ISSUE THREAD

**Issue by ZhangLanqiu** [V1sk/HttpRequestExample#2]
我把你的代码 clone 了下来然而一运行就抛了个这个，我也不知咋改好了
handler.post(new Runnable() {
                        @Override
                        public void run() {
                            try {
                                String json = response.body().string(); //这行报错
                                requestCallback.onSuccess(json);
                            } catch (IOException e) {
                                e.printStackTrace();
                            }
                        }
                    });

我什么都没动，难道是我的姿势有问题?

**Comment by ghost** [comment]
这个代码的handler是在主线程中new出来的,所以你通过主线程post的请求是在主线程中产生,解决方案有两种,一种是在子线程中new handler,一种是在handler.post里面再开一个子线程进行请求

**Comment by ZhangLanqiu** [comment]
@RyanYG  handler.post(),中 Runnable 还是在主线程啊！ 我说呢！谢了！ 唉，作者坑啊！希望以后严谨一点！　整的我好尴尬！

**Comment by V1sk** [comment]
已更正，操作是要回调到主线程，OkHttp的Response对象不能在主线程操作，以后会更严谨，感谢提出issues。
